# Generated by Django 5.1.3 on 2024-11-26 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome da cidade', max_length=255, unique=True, verbose_name='Nome da Cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(help_text='Informe a sigla da Unidade Federativa', max_length=2, unique=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Unidade Federal',
                'verbose_name_plural': 'Unidades Federais',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome', max_length=255, verbose_name='Nome')),
                ('email', models.CharField(help_text='Informe o e-mail', max_length=255, verbose_name='E-mail')),
                ('telefone', models.CharField(help_text='Informe o telefone', max_length=20, verbose_name='Telefone')),
                ('cpf', models.CharField(help_text='Informe o CPF', max_length=11, verbose_name='CPF')),
                ('data_nasc', models.DateField(default='2000-01-01', help_text='Informe a data de nascimento', verbose_name='Data de Nascimento')),
                ('cidade', models.ForeignKey(blank=True, help_text='Selecione a cidade', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(blank=True, help_text='Selecione a Unidade Federal', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.uf', verbose_name='Unidade Federal'),
        ),
    ]
