# Generated by Django 5.1.3 on 2024-12-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Area')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nome_do_pai', models.CharField(max_length=100, verbose_name='Nome do pai')),
                ('nome_da_mae', models.CharField(max_length=100, verbose_name='Nome da mãe')),
                ('cpf', models.CharField(max_length=12, verbose_name='CPF')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.CharField(max_length=200, verbose_name='E-mail')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade da pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='OcupacaoPessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Ocupação de pessoas')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo da Avaliação')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=11, verbose_name='Turno')),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, verbose_name='Unidade Federativa')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da disciplina')),
                ('area_saber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areasaber', verbose_name='Área do Saber')),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoa')),
                ('RA', models.CharField(max_length=16, verbose_name='Registro Acadêmico')),
            ],
            bases=('app.pessoa',),
        ),
        migrations.CreateModel(
            name='InstituicaoEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Instituição')),
                ('site', models.CharField(max_length=200, verbose_name='Site')),
                ('telefone', models.CharField(max_length=21, verbose_name='Telefone')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('carga_horaria_total', models.IntegerField(verbose_name='Carga Horaria Total')),
                ('duracao_meses', models.IntegerField(verbose_name='Duração em Meses')),
                ('area_saber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areasaber', verbose_name='Área do Saber')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicaoensino', verbose_name='Instituição de Ensino')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data de aplicação')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ocupacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ocupacaopessoas', verbose_name='Ocupação da pessoa'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turno', verbose_name='Turno')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaPorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turno', verbose_name='Turno')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uf', verbose_name='Unidade Federativa'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicaoensino', verbose_name='Instituição de Ensino')),
                ('estudante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estudante', verbose_name='Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_faltas', models.IntegerField(verbose_name='Numero de Faltas')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina')),
                ('estudante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estudante', verbose_name='Pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='estudante',
            name='Turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='estudante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estudante', verbose_name='Pessoa'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('nota', models.IntegerField(verbose_name='Nota')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina')),
                ('tipoavaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoavaliacao', verbose_name='Tipo da Avaliação')),
                ('estudante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.estudante', verbose_name='Pessoa')),
            ],
        ),
    ]
